version: '3.8'

name: 'unievents'

services:
  db:
    image: postgres:15-alpine
    container_name: unievents-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - .data:/var/lib/postgresql/data